using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace SecureNotesWin.Localization
{
    public class LocalizationManager : INotifyPropertyChanged
    {
        private static LocalizationManager? _instance;
        private AppLanguage _currentLanguage = AppLanguage.ENGLISH;
        private Dictionary<AppLanguage, Dictionary<string, string>> _translations = new();

        public static LocalizationManager Instance => _instance ??= new LocalizationManager();

        public event PropertyChangedEventHandler? PropertyChanged;

        public AppLanguage CurrentLanguage
        {
            get => _currentLanguage;
            set
            {
                if (_currentLanguage != value)
                {
                    _currentLanguage = value;
                    OnPropertyChanged(nameof(CurrentLanguage));
                    // "Item[]" is the correct notification for WPF indexer bindings —
                    // this forces every {loc:Loc key} binding on every open window to
                    // re-read Item[key] from the new language dictionary immediately.
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
                }
            }
        }

        public string this[string key] => GetString(key);

        private LocalizationManager()
        {
            InitializeTranslations();
        }

        private void InitializeTranslations()
        {
            // English
            _translations[AppLanguage.ENGLISH] = new Dictionary<string, string>
            {
                { "settings", "Settings" },
                { "appearance", "Appearance" },
                { "theme", "Theme" },
                { "security", "Security" },
                { "auto_lock", "Auto-Lock" },
                { "change_password", "Change Master Password" },
                { "backup_restore", "BACKUP & RESTORE" },
                { "import_section", "IMPORT" },
                { "backup_to_zip", "Back up to Zip" },
                { "restore_from_zip", "Restore from Zip" },
                { "import_journey", "Import from Journey" },
                { "import_dayone", "Import from DayOne" },
                { "about", "About" },
                { "version", "Version" },
                { "language", "Language" },
                { "select_language", "Select Language" },
                { "cancel", "Cancel" },
                { "save", "Save" },
                { "done", "Done" },
                { "close", "Close" },
                { "search_notes", "Search notes..." },
                { "no_notes", "No notes yet\nCreate a book then add your notes" },
                { "unlock_vault", "Unlock Vault" },
                { "master_password", "Master Password" },
                { "create_vault", "Create Vault" },
                { "secure_notes", "Secure Notes" },
                { "enter_password", "Enter your master password to unlock" },
                { "incorrect_password", "Incorrect password or wrong vault file" },
                { "vault_file", "Vault File" },
                { "browse", "Browse" },
                { "new_note", "New Note" },
                { "new_diary", "New Diary" },
                { "move_to_notebook", "Move to Notebook" },
                { "move_to_diary", "Move to Diary" },
                { "delete", "Delete" },
                { "add_tags", "Add Tags" },
                { "tags", "Tags" },
                { "new_tag", "New tag..." },
                { "lock_after", "Lock after" },
                { "minutes", "Minutes" },
                { "seconds", "Seconds" },
                { "date_format", "Date Format" },
                { "time_format", "Time Format" },
                { "general", "General" },
                { "saving", "Saving..." },
                { "saved", "Saved" },
                { "unlock", "Unlock" },
                { "create", "Create" },
                { "set_master_password", "Set Master Password" },
                { "confirm_password", "Confirm Password" },
                { "passwords_do_not_match", "Passwords do not match" },
                { "loading", "Loading..." },
                { "password_too_short", "Password must be at least 6 characters" },
                { "notes_count", "notes" },
                { "rename", "Edit" },
                { "edit", "Edit" },
                { "lock_vault", "Lock Vault" },
                { "books", "BOOKS" },
                { "new_notebook", "New Notebook" },
                { "rename_book", "Edit Book" },
                { "notebook_name", "Notebook name" },
                { "diary_name", "Diary name" },
                { "type", "Type" },
                { "notebook", "Notebook" },
                { "diary", "Diary" },
                { "icon", "Icon" },
                { "name_empty_error", "Name cannot be empty" },
                { "new_tag_title", "New Tag" },
                { "tag_name", "Tag name" },
                { "color", "Color" },
                { "delete_book_title", "Delete {0}" },
                { "delete_book_msg", "Are you sure you want to delete {0}? This will also delete all notes within it." },
                { "yes_delete", "Yes, Delete" },
                { "yes", "Yes" },
                { "no", "No" },
                { "delete_note_title", "Delete Note" },
                { "delete_note_msg", "Are you sure you want to delete '{0}'?" },
                { "add_book", "Add Book" },
                { "manage_tags", "Manage Tags" },
                { "select_or_create", "Select or create a note" },
                { "move_to_book", "Move to Book" },
                { "which_book", "Which book do you want to move to?" },
                { "move_btn", "Move" },
                { "untitled", "Untitled" },
                { "ink_black", "Ink Black" },
                { "paper_white", "Paper White" },
                { "light_mode", "Light Mode" },
                { "dark_mode", "Dark Mode" },
                { "follow_system", "Follow System" },
                { "current_password", "Current Password" },
                { "new_password", "New Password" },
                { "confirm_new_password", "Confirm New Password" },
                { "password_updated_success", "Password updated successfully!" },
                { "export_success", "Exported successfully" },
                { "export_failed", "Export failed" },
                { "import_success", "Imported {0} note(s) from {1}." },
                { "import_failed", "Import failed: {0}" },
                { "open_vault", "Open Vault" },
                { "create_new_vault", "Create New Vault" },
                { "open_existing_vault", "Open Existing Vault" },
                { "choose_vault_access", "Choose how to access your encrypted notes" },
                { "password_weak", "Weak" },
                { "password_fair", "Fair" },
                { "password_good", "Good" },
                { "password_strong", "Strong" },
                { "master_password_label", "Master password:" },
                { "confirm_password_label", "Confirm password:" },
                { "create_new_vault_desc", "Create a master password and choose where to store your encrypted .kdbx vault. This file is compatible with KeePass and the Secure Notes Android app." },
                { "no_vault_found", "No vault found. Please open or create one." },
                { "incorrect_password_vault", "Incorrect password or corrupted vault." },
                { "failed_to_create_vault", "Failed to create vault. Check permissions." },
                { "please_enter_password", "Please enter a password." },
                { "create_vault_ellipsis", "Create Vault\u2026" },
                { "create_new_vault_ellipsis", "Create new vault\u2026" },
                { "select_theme", "Select Theme" },
                { "auto_lock_timeout", "Auto-Lock Timeout" },
                { "select_date_format", "Select Date Format" },
                { "select_time_format", "Select Time Format" },
                { "update_vault_password", "Update your vault password" },
                { "backup_to_zip_sub", "Save all notes as a Markdown ZIP backup" },
                { "restore_from_zip_sub", "Restore notes from a Markdown ZIP backup" },
                { "import_journey_sub", "Import Journey.cloud diary (JSON ZIP)" },
                { "import_dayone_sub", "Import DayOne diary (JSON ZIP)" },
                { "backup_book_selector_title", "Back up which book?" },
                { "restore_book_selector_title", "Restore to which book?" },
                { "import_book_selector_title", "Import {0} to which book?" },
                { "backup_success", "Backup complete." },
                { "restore_success", "Restored {0} note(s)." },
                { "biometric_unlock", "Biometric Unlock" },
                { "edited", "Edited" },
                { "attachments", "Attachments" },
                { "import_to_which_book", "Import to which book?" },
{ "import_complete", "Import complete" },
{ "imported_notes", "Imported {0} note(s)." },
{ "imported_notes_from", "Imported {0} note(s) from {1}." },
{ "export_which_book", "Export which book?" },
{ "export_complete", "Export complete." },
{ "import", "Import" },
{ "export", "Export" },
{ "error", "Error" },
{ "current_password_incorrect", "Current password is incorrect." },
{ "password_changed_successfully", "Password changed successfully." },
{ "failed_change_password", "Failed to change password." },
{ "import_from", "Import from {0}" },
{ "import_to_book", "Import {0} to which book?" },
{ "enter_current_password_error", "Please enter your current password." },
{ "new_password_too_short", "New password must be at least 6 characters." },
{ "change", "Change" },
{ "lock_after_inactivity", "Lock vault after inactivity" },
            
                { "add", "Add" },
                { "edit_notebook", "Edit Notebook" },
                { "name", "Name" },
            };

            // Spanish
            _translations[AppLanguage.SPANISH] = new Dictionary<string, string>
            {
                { "settings", "Ajustes" },
                { "appearance", "Apariencia" },
                { "theme", "Tema" },
                { "security", "Seguridad" },
                { "auto_lock", "Bloqueo automático" },
                { "change_password", "Cambiar contraseña maestra" },
                { "backup_restore", "COPIA DE SEGURIDAD Y RESTAURACIÓN" },
                { "import_section", "IMPORTAR" },
                { "backup_to_zip", "Hacer copia de seguridad en Zip" },
                { "restore_from_zip", "Restaurar desde Zip" },
                { "import_journey", "Importar desde Journey" },
                { "import_dayone", "Importar desde DayOne" },
                { "about", "Acerca de" },
                { "version", "Versión" },
                { "language", "Idioma" },
                { "select_language", "Seleccionar idioma" },
                { "cancel", "Cancelar" },
                { "save", "Guardar" },
                { "done", "Listo" },
                { "close", "Cerrar" },
                { "search_notes", "Buscar notas..." },
                { "no_notes", "No hay notas aún\nCrea un libro y luego agrega tus notas" },
                { "unlock_vault", "Desbloquear Bóveda" },
                { "master_password", "Contraseña Maestra" },
                { "create_vault", "Crear Bóveda" },
                { "secure_notes", "Notas Seguras" },
                { "enter_password", "Ingrese su contraseña maestra para desbloquear" },
                { "incorrect_password", "Contraseña incorrecta o archivo de bóveda erróneo" },
                { "vault_file", "Archivo de Bóveda" },
                { "browse", "Explorar" },
                { "new_note", "Nueva Nota" },
                { "new_diary", "Nuevo Diario" },
                { "move_to_notebook", "Mover a Libro" },
                { "move_to_diary", "Mover a Diario" },
                { "delete", "Eliminar" },
                { "add_tags", "Añadir Etiquetas" },
                { "tags", "Etiquetas" },
                { "new_tag", "Nueva etiqueta..." },
                { "lock_after", "Bloquear después de" },
                { "minutes", "Minutos" },
                { "seconds", "Segundos" },
                { "date_format", "Formato de Fecha" },
                { "time_format", "Formato de Hora" },
                { "general", "General" },
                { "saving", "Guardando..." },
                { "saved", "Guardado" },
                { "unlock", "Desbloquear" },
                { "create", "Crear" },
                { "books", "LIBROS" },
                { "ink_black", "Negro Tinta" },
                { "paper_white", "Blanco Papel" },
                { "light_mode", "Modo claro" },
                { "dark_mode", "Modo oscuro" },
                { "follow_system", "Seguir sistema" },
                { "current_password", "Contraseña actual" },
                { "new_password", "Nueva contraseña" },
                { "confirm_new_password", "Confirmar nueva contraseña" },
                { "update_vault_password", "Actualiza tu contraseña del vault" },
                { "open_vault", "Abrir Bóveda" },
                { "create_new_vault", "Crear Nueva Bóveda" },
                { "open_existing_vault", "Abrir Bóveda Existente" },
                { "choose_vault_access", "Elige cómo acceder a tus notas cifradas" },
                { "password_fair", "Regular" },
                { "master_password_label", "Contraseña maestra:" },
                { "confirm_password_label", "Confirmar contraseña:" },
                { "create_new_vault_desc", "Crea una contraseña maestra y elige dónde almacenar tu bóveda .kdbx cifrada. Este archivo es compatible con KeePass y la app Secure Notes para Android." },
                { "no_vault_found", "No se encontró bóveda. Por favor, abre o crea una." },
                { "incorrect_password_vault", "Contraseña incorrecta o bóveda corrupta." },
                { "failed_to_create_vault", "Error al crear la bóveda. Comprueba los permisos." },
                { "please_enter_password", "Por favor, introduce una contraseña." },
                { "create_vault_ellipsis", "Crear Bóveda\u2026" },
                { "create_new_vault_ellipsis", "Crear nueva bóveda\u2026" },
                { "backup_to_zip_sub", "Guardar todas las notas como copia de seguridad ZIP" },
                { "restore_from_zip_sub", "Restaurar notas desde una copia de seguridad ZIP" },
                { "import_journey_sub", "Importar diario Journey.cloud (ZIP JSON)" },
                { "import_dayone_sub", "Importar diario DayOne (ZIP JSON)" },
                { "backup_book_selector_title", "¿De qué libro hacer copia de seguridad?" },
                { "restore_book_selector_title", "¿A qué libro restaurar?" },
                { "import_book_selector_title", "¿Importar {0} a qué libro?" },
                { "backup_success", "Copia de seguridad completada." },
                { "restore_success", "Se restauraron {0} nota(s)." },
                { "import_success", "Se importaron {0} nota(s) de {1}." },
                { "select_date_format", "Seleccionar formato de fecha" },
{ "select_time_format", "Seleccionar formato de hora" },
{ "select_theme", "Seleccionar tema" },
{ "import_to_which_book", "¿Importar a qué libro?" },
{ "import_complete", "Importación completada" },
{ "imported_notes", "Importadas {0} nota(s)." },
{ "imported_notes_from", "Importadas {0} nota(s) desde {1}." },
{ "export_which_book", "¿Exportar qué libro?" },
{ "export_complete", "Exportación completada" },
{ "import", "Importar" },
{ "export", "Exportar" },
{ "error", "Error" },
{ "current_password_incorrect", "La contraseña actual es incorrecta." },
{ "password_changed_successfully", "Contraseña cambiada correctamente." },
{ "failed_change_password", "Error al cambiar la contraseña." },
{ "import_from", "Importar desde {0}" },
{ "import_to_book", "Importar {0} a qué libro?" },
{ "enter_current_password_error", "Por favor, introduce tu contraseña actual." },
{ "new_password_too_short", "La nueva contraseña debe tener al menos 6 caracteres." },
{ "passwords_do_not_match", "Las contraseñas no coinciden." },
{ "change", "Cambiar" },
{ "auto_lock_timeout", "Tiempo de bloqueo automático" },
{ "lock_after_inactivity", "Bloquear la bóveda tras inactividad" },
            
                { "rename", "Editar" },
                { "edit", "Editar" },
                { "rename_book", "Editar Libro" },
                { "notebook", "Cuaderno" },
                { "diary", "Diario" },
                { "yes", "Sí" },
                { "yes_delete", "Sí, Eliminar" },
                { "no", "No" },
                { "delete_note_title", "Eliminar Nota" },
                { "add_book", "Agregar Libro" },
                { "manage_tags", "Gestionar Etiquetas" },
                { "select_or_create", "Seleccionar o crear una nota" },
                { "move_to_book", "Mover al Libro" },
                { "which_book", "¿A qué libro quieres moverlo?" },
                { "move_btn", "Mover" },
            
                { "add", "Añadir" },
                { "edit_notebook", "Editar Cuaderno" },
                { "name", "Nombre" },
            
                { "icon", "Icono" },
            };

            // French
            _translations[AppLanguage.FRENCH] = new Dictionary<string, string>
            {
                { "settings", "Paramètres" },
                { "appearance", "Apparence" },
                { "theme", "Thème" },
                { "security", "Sécurité" },
                { "auto_lock", "Verrouillage automatique" },
                { "change_password", "Changer le mot de passe maître" },
                { "backup_restore", "SAUVEGARDE ET RESTAURATION" },
                { "import_section", "IMPORTER" },
                { "backup_to_zip", "Sauvegarder en Zip" },
                { "restore_from_zip", "Restaurer depuis Zip" },
                { "about", "À propos" },
                { "version", "Version" },
                { "language", "Langue" },
                { "select_language", "Choisir la langue" },
                { "cancel", "Annuler" },
                { "save", "Enregistrer" },
                { "done", "Terminé" },
                { "close", "Fermer" },
                { "search_notes", "Rechercher des notes..." },
                { "no_notes", "Aucune note pour le moment\nCréez un carnet puis ajoutez vos notes" },
                { "unlock_vault", "Déverrouiller le coffre" },
                { "master_password", "Mot de passe maître" },
                { "create_vault", "Créer un coffre" },
                { "secure_notes", "Notes Sécurisées" },
                { "new_note", "Nouvelle note" },
                { "new_diary", "Nouveau journal" },
                { "delete", "Supprimer" },
                { "books", "CARNETS" },
                { "ink_black", "Noir Encre" },
                { "paper_white", "Blanc Papier" },
                { "light_mode", "Mode clair" },
                { "dark_mode", "Mode sombre" },
                { "follow_system", "Suivre le système" },
                { "update_vault_password", "Mettre à jour votre mot de passe de coffre" },
                { "open_vault", "Ouvrir le coffre" },
                { "create_new_vault", "Créer un nouveau coffre" },
                { "open_existing_vault", "Ouvrir un coffre existant" },
                { "choose_vault_access", "Choisissez comment accéder à vos notes chiffrées" },
                { "password_fair", "Passable" },
                { "master_password_label", "Mot de passe maître :" },
                { "confirm_password_label", "Confirmer le mot de passe :" },
                { "create_new_vault_desc", "Créez un mot de passe maître et choisissez où stocker votre coffre .kdbx chiffré. Ce fichier est compatible avec KeePass et l'application Secure Notes pour Android." },
                { "no_vault_found", "Aucun coffre trouvé. Veuillez en ouvrir ou en créer un." },
                { "incorrect_password_vault", "Mot de passe incorrect ou coffre corrompu." },
                { "failed_to_create_vault", "Impossible de créer le coffre. Vérifiez les permissions." },
                { "please_enter_password", "Veuillez saisir un mot de passe." },
                { "create_vault_ellipsis", "Créer le coffre\u2026" },
                { "create_new_vault_ellipsis", "Créer un nouveau coffre\u2026" },
                { "backup_to_zip_sub", "Enregistrer toutes les notes dans un ZIP de sauvegarde" },
                { "restore_from_zip_sub", "Restaurer les notes depuis un ZIP de sauvegarde" },
                { "import_journey", "Importer depuis Journey" },
                { "import_dayone", "Importer depuis DayOne" },
                { "import_journey_sub", "Importer le journal Journey.cloud (ZIP JSON)" },
                { "import_dayone_sub", "Importer le journal DayOne (ZIP JSON)" },
                { "backup_book_selector_title", "Sauvegarder quel carnet ?" },
                { "restore_book_selector_title", "Restaurer vers quel carnet ?" },
                { "import_book_selector_title", "Importer {0} vers quel carnet ?" },
                { "backup_success", "Sauvegarde terminée." },
                { "restore_success", "{0} note(s) restaurée(s)." },
                { "import_success", "{0} note(s) importée(s) depuis {1}." },
                { "date_format", "Format de Date" },
                { "time_format", "Format d'Heure" },
                { "general", "Général" },
                { "lock_vault", "Verrouiller le coffre" },
                { "select_date_format", "Sélectionner le format de date" },
{ "select_time_format", "Sélectionner le format de l'heure" },
{ "select_theme", "Choisir le thème" },
{ "import_to_which_book", "Importer dans quel carnet ?" },
{ "import_complete", "Importation terminée" },
{ "imported_notes", "{0} note(s) importée(s)." },
{ "imported_notes_from", "{0} note(s) importée(s) depuis {1}." },
{ "export_which_book", "Exporter quel carnet ?" },
{ "export_complete", "Export terminé" },
{ "import", "Importer" },
{ "export", "Exporter" },
{ "error", "Erreur" },
{ "current_password_incorrect", "Le mot de passe actuel est incorrect." },
{ "password_changed_successfully", "Mot de passe changé avec succès." },
{ "failed_change_password", "Échec du changement de mot de passe." },
{ "import_from", "Importer depuis {0}" },
{ "import_to_book", "Importer {0} dans quel carnet ?" },
{ "enter_current_password_error", "Veuillez saisir votre mot de passe actuel." },
{ "new_password_too_short", "Le nouveau mot de passe doit contenir au moins 6 caractères." },
{ "passwords_do_not_match", "Les mots de passe ne correspondent pas." },
{ "new_password", "Nouveau mot de passe" },
{ "confirm_new_password", "Confirmer le nouveau mot de passe" },
{ "change", "Changer" },
{ "current_password", "Mot de passe actuel" },
{ "auto_lock_timeout", "Délai de verrouillage automatique" },
{ "lock_after_inactivity", "Verrouiller le coffre après inactivité" },
{ "minutes", "Minutes" },
{ "seconds", "Secondes" },


            
                { "rename", "Modifier" },
                { "edit", "Modifier" },
                { "rename_book", "Modifier le Carnet" },
                { "notebook", "Carnet" },
                { "diary", "Journal" },
                { "yes", "Oui" },
                { "yes_delete", "Oui, Supprimer" },
                { "no", "Non" },
                { "delete_note_title", "Supprimer la Note" },
                { "add_book", "Ajouter un Carnet" },
                { "manage_tags", "Gérer les Étiquettes" },
                { "select_or_create", "Sélectionner ou créer une note" },
                { "move_to_book", "Déplacer vers Carnet" },
                { "which_book", "Dans quel carnet voulez-vous déplacer ?" },
                { "move_btn", "Déplacer" },
            
                { "add", "Ajouter" },
                { "edit_notebook", "Modifier le Carnet" },
                { "name", "Nom" },
            
                { "icon", "Icône" },
            };

            // German
            _translations[AppLanguage.GERMAN] = new Dictionary<string, string>
            {
                { "settings", "Einstellungen" },
                { "appearance", "Aussehen" },
                { "theme", "Design" },
                { "security", "Sicherheit" },
                { "auto_lock", "Automatische Sperre" },
                { "change_password", "Master-Passwort ändern" },
                { "backup_restore", "SICHERUNG & WIEDERHERSTELLUNG" },
                { "import_section", "IMPORTIEREN" },
                { "backup_to_zip", "Als Zip sichern" },
                { "restore_from_zip", "Aus Zip wiederherstellen" },
                { "about", "Über" },
                { "version", "Version" },
                { "language", "Sprache" },
                { "select_language", "Sprache wählen" },
                { "cancel", "Abbrechen" },
                { "save", "Speichern" },
                { "done", "Fertig" },
                { "close", "Schließen" },
                { "search_notes", "Notizen suchen..." },
                { "no_notes", "Noch keine Notizen\nErstelle ein Buch und füge dann deine Notizen hinzu" },
                { "unlock_vault", "Tresor entsperren" },
                { "master_password", "Master-Passwort" },
                { "create_vault", "Tresor erstellen" },
                { "secure_notes", "Sichere Notizen" },
                { "new_note", "Neue Notiz" },
                { "new_diary", "Neues Tagebuch" },
                { "delete", "Löschen" },
                { "books", "BÜCHER" },
                { "ink_black", "Tiefschwarz" },
                { "paper_white", "Papierweiß" },
                { "light_mode", "Hell" },
                { "dark_mode", "Dunkel" },
                { "follow_system", "Systemstandard" },
                { "update_vault_password", "Tresor-Passwort aktualisieren" },
                { "open_vault", "Tresor öffnen" },
                { "create_new_vault", "Neuen Tresor erstellen" },
                { "open_existing_vault", "Vorhandenen Tresor öffnen" },
                { "choose_vault_access", "Wähle, wie du auf deine verschlüsselten Notizen zugreifst" },
                { "password_fair", "Mäßig" },
                { "master_password_label", "Master-Passwort:" },
                { "confirm_password_label", "Passwort bestätigen:" },
                { "create_new_vault_desc", "Erstelle ein Master-Passwort und wähle, wo dein verschlüsselter .kdbx-Tresor gespeichert wird. Diese Datei ist mit KeePass und der Secure Notes Android-App kompatibel." },
                { "no_vault_found", "Kein Tresor gefunden. Bitte öffne oder erstelle einen." },
                { "incorrect_password_vault", "Falsches Passwort oder beschädigter Tresor." },
                { "failed_to_create_vault", "Tresor konnte nicht erstellt werden. Überprüfe die Berechtigungen." },
                { "please_enter_password", "Bitte gib ein Passwort ein." },
                { "create_vault_ellipsis", "Tresor erstellen\u2026" },
                { "create_new_vault_ellipsis", "Neuen Tresor erstellen\u2026" },
                { "backup_to_zip_sub", "Alle Notizen als Markdown-ZIP-Backup speichern" },
                { "restore_from_zip_sub", "Notizen aus einem Markdown-ZIP-Backup wiederherstellen" },
                { "import_journey", "Aus Journey importieren" },
                { "import_dayone", "Aus DayOne importieren" },
                { "import_journey_sub", "Journey.cloud-Tagebuch importieren (JSON-ZIP)" },
                { "import_dayone_sub", "DayOne-Tagebuch importieren (JSON-ZIP)" },
                { "backup_book_selector_title", "Welches Notizbuch sichern?" },
                { "restore_book_selector_title", "In welches Notizbuch wiederherstellen?" },
                { "import_book_selector_title", "{0} in welches Notizbuch importieren?" },
                { "backup_success", "Sicherung abgeschlossen." },
                { "restore_success", "{0} Notiz(en) wiederhergestellt." },
                { "import_success", "{0} Notiz(en) aus {1} importiert." },
                { "date_format", "Datumsformat" },
                { "time_format", "Zeitformat" },
                { "general", "Allgemein" },
                { "lock_vault", "Tresor sperren" },
                { "select_date_format", "Datumsformat auswählen" },
{ "select_time_format", "Zeitformat auswählen" },
{ "select_theme", "Design auswählen" },
{ "import_to_which_book", "In welches Buch importieren?" },
{ "import_complete", "Import abgeschlossen" },
{ "imported_notes", "{0} Notiz(en) importiert." },
{ "imported_notes_from", "{0} Notiz(en) aus {1} importiert." },
{ "export_which_book", "Welches Buch exportieren?" },
{ "export_complete", "Export abgeschlossen" },
{ "import", "Importieren" },
{ "export", "Exportieren" },
{ "error", "Fehler" },
{ "current_password_incorrect", "Aktuelles Passwort ist falsch." },
{ "password_changed_successfully", "Passwort erfolgreich geändert." },
{ "failed_change_password", "Passwort konnte nicht geändert werden." },
{ "import_from", "Importieren von {0}" },
{ "import_to_book", "{0} in welches Buch importieren?" },
{ "enter_current_password_error", "Bitte geben Sie Ihr aktuelles Passwort ein." },
{ "new_password_too_short", "Das neue Passwort muss mindestens 6 Zeichen lang sein." },
{ "passwords_do_not_match", "Die Passwörter stimmen nicht überein." },
{ "new_password", "Neues Passwort" },
{ "confirm_new_password", "Neues Passwort bestätigen" },
{ "change", "Ändern" },
{ "current_password", "Aktuelles Passwort" },
{ "auto_lock_timeout", "Zeitlimit für automatische Sperre" },
{ "lock_after_inactivity", "Tresor nach Inaktivität sperren" },
{ "minutes", "Minuten" },
{ "seconds", "Sekunden" },
            
                { "rename", "Bearbeiten" },
                { "edit", "Bearbeiten" },
                { "rename_book", "Buch Bearbeiten" },
                { "notebook", "Notizbuch" },
                { "diary", "Tagebuch" },
                { "yes", "Ja" },
                { "yes_delete", "Ja, Löschen" },
                { "no", "Nein" },
                { "delete_note_title", "Notiz Löschen" },
                { "add_book", "Buch Hinzufügen" },
                { "manage_tags", "Tags Verwalten" },
                { "select_or_create", "Notiz auswählen oder erstellen" },
                { "move_to_book", "In Buch verschieben" },
                { "which_book", "In welches Buch möchten Sie verschieben?" },
                { "move_btn", "Verschieben" },
            
                { "add", "Hinzufügen" },
                { "edit_notebook", "Notizbuch Bearbeiten" },
                { "name", "Name" },
            
                { "icon", "Symbol" },
            };

            // Italian
            _translations[AppLanguage.ITALIAN] = new Dictionary<string, string>
            {
                { "settings", "Impostazioni" },
                { "appearance", "Aspetto" },
                { "theme", "Tema" },
                { "security", "Sicurezza" },
                { "auto_lock", "Blocco automatico" },
                { "change_password", "Cambia password principale" },
                { "backup_restore", "BACKUP E RIPRISTINO" },
                { "import_section", "IMPORTA" },
                { "backup_to_zip", "Esegui backup in Zip" },
                { "restore_from_zip", "Ripristina da Zip" },
                { "about", "Informazioni" },
                { "version", "Versione" },
                { "language", "Lingua" },
                { "select_language", "Seleziona lingua" },
                { "cancel", "Annulla" },
                { "save", "Salva" },
                { "done", "Fatto" },
                { "close", "Chiudi" },
                { "search_notes", "Cerca note..." },
                { "no_notes", "Nessuna nota presente\nCrea un libro e poi aggiungi le tue note" },
                { "unlock_vault", "Sblocca cassaforte" },
                { "master_password", "Password principale" },
                { "create_vault", "Crea cassaforte" },
                { "secure_notes", "Note sicure" },
                { "new_note", "Nuova nota" },
                { "new_diary", "Nuovo diario" },
                { "delete", "Elimina" },
                { "books", "LIBRI" },
                { "ink_black", "Nero Inchiostro" },
                { "paper_white", "Carta Bianca" },
                { "light_mode", "Modalità chiara" },
                { "dark_mode", "Modalità scura" },
                { "follow_system", "Segui il sistema" },
                { "update_vault_password", "Aggiorna la password del vault" },
                { "open_vault", "Apri cassaforte" },
                { "create_new_vault", "Crea nuova cassaforte" },
                { "open_existing_vault", "Apri cassaforte esistente" },
                { "choose_vault_access", "Scegli come accedere alle tue note crittografate" },
                { "password_fair", "Discreto" },
                { "master_password_label", "Password principale:" },
                { "confirm_password_label", "Conferma password:" },
                { "create_new_vault_desc", "Crea una password principale e scegli dove salvare la tua cassaforte .kdbx crittografata. Questo file è compatibile con KeePass e l'app Secure Notes per Android." },
                { "no_vault_found", "Nessuna cassaforte trovata. Aprila o creane una." },
                { "incorrect_password_vault", "Password errata o cassaforte corrotta." },
                { "failed_to_create_vault", "Impossibile creare la cassaforte. Controlla i permessi." },
                { "please_enter_password", "Inserisci una password." },
                { "create_vault_ellipsis", "Crea cassaforte\u2026" },
                { "create_new_vault_ellipsis", "Crea nuova cassaforte\u2026" },
                { "backup_to_zip_sub", "Salva tutte le note come backup ZIP Markdown" },
                { "restore_from_zip_sub", "Ripristina le note da un backup ZIP Markdown" },
                { "import_journey", "Importa da Journey" },
                { "import_dayone", "Importa da DayOne" },
                { "import_journey_sub", "Importa diario Journey.cloud (ZIP JSON)" },
                { "import_dayone_sub", "Importa diario DayOne (ZIP JSON)" },
                { "backup_book_selector_title", "Di quale quaderno eseguire il backup?" },
                { "restore_book_selector_title", "In quale quaderno ripristinare?" },
                { "import_book_selector_title", "Importare {0} in quale quaderno?" },
                { "backup_success", "Backup completato." },
                { "restore_success", "{0} nota/e ripristinata/e." },
                { "import_success", "{0} nota/e importata/e da {1}." },
                { "date_format", "Formato Data" },
                { "time_format", "Formato Ora" },
                { "general", "Generale" },
                { "lock_vault", "Blocca cassaforte" },
                { "select_date_format", "Seleziona formato data" },
{ "select_time_format", "Seleziona formato ora" },
{ "select_theme", "Seleziona tema" },
{ "import_to_which_book", "In quale libro importare?" },
{ "import_complete", "Importazione completata" },
{ "imported_notes", "{0} nota(e) importate." },
{ "imported_notes_from", "{0} nota(e) importate da {1}." },
{ "export_which_book", "Quale libro esportare?" },
{ "export_complete", "Esportazione completata" },
{ "import", "Importa" },
{ "export", "Esporta" },
{ "error", "Errore" },
{ "current_password_incorrect", "La password attuale non è corretta." },
{ "password_changed_successfully", "Password modificata con successo." },
{ "failed_change_password", "Modifica password non riuscita." },
{ "import_from", "Importa da {0}" },
{ "import_to_book", "Importare {0} in quale libro?" },
{ "enter_current_password_error", "Inserisci la tua password attuale." },
{ "new_password_too_short", "La nuova password deve contenere almeno 6 caratteri." },
{ "passwords_do_not_match", "Le password non corrispondono." },
{ "new_password", "Nuova password" },
{ "confirm_new_password", "Conferma nuova password" },
{ "change", "Cambia" },
{ "current_password", "Password attuale" },
{ "auto_lock_timeout", "Timeout blocco automatico" },
{ "lock_after_inactivity", "Blocca il vault dopo inattività" },
{ "minutes", "Minuti" },
{ "seconds", "Secondi" },
            
                { "rename", "Modifica" },
                { "edit", "Modifica" },
                { "rename_book", "Modifica Libro" },
                { "notebook", "Quaderno" },
                { "diary", "Diario" },
                { "yes", "Sì" },
                { "yes_delete", "Sì, Elimina" },
                { "no", "No" },
                { "delete_note_title", "Elimina Nota" },
                { "add_book", "Aggiungi Libro" },
                { "manage_tags", "Gestisci Etichette" },
                { "select_or_create", "Seleziona o crea una nota" },
                { "move_to_book", "Sposta nel Libro" },
                { "which_book", "In quale libro vuoi spostare?" },
                { "move_btn", "Sposta" },
            
                { "add", "Aggiungi" },
                { "edit_notebook", "Modifica Quaderno" },
                { "name", "Nome" },
            
                { "icon", "Icona" },
            };

            // Portuguese
            _translations[AppLanguage.PORTUGUESE] = new Dictionary<string, string>
            {
                { "settings", "Configurações" },
                { "appearance", "Aparência" },
                { "theme", "Tema" },
                { "security", "Segurança" },
                { "auto_lock", "Bloqueio automático" },
                { "change_password", "Alterar senha mestre" },
                { "backup_restore", "BACKUP E RESTAURAÇÃO" },
                { "import_section", "IMPORTAR" },
                { "backup_to_zip", "Fazer backup em Zip" },
                { "restore_from_zip", "Restaurar do Zip" },
                { "about", "Sobre" },
                { "version", "Versão" },
                { "language", "Idioma" },
                { "select_language", "Selecionar idioma" },
                { "cancel", "Cancelar" },
                { "save", "Salvar" },
                { "done", "Concluído" },
                { "close", "Fechar" },
                { "search_notes", "Pesquisar notas..." },
                { "no_notes", "Nenhuma nota encontrada\nCrie um livro e adicione suas notas" },
                { "unlock_vault", "Desbloquear cofre" },
                { "master_password", "Senha mestre" },
                { "create_vault", "Criar cofre" },
                { "secure_notes", "Notas seguras" },
                { "new_note", "Nova nota" },
                { "new_diary", "Novo diário" },
                { "delete", "Eliminar" },
                { "books", "LIVROS" },
                { "ink_black", "Preto Tinta" },
                { "paper_white", "Papel Branco" },
                { "light_mode", "Modo claro" },
                { "dark_mode", "Modo escuro" },
                { "follow_system", "Seguir o sistema" },
                { "update_vault_password", "Atualizar sua senha do cofre" },
                { "open_vault", "Abrir cofre" },
                { "create_new_vault", "Criar novo cofre" },
                { "open_existing_vault", "Abrir cofre existente" },
                { "choose_vault_access", "Escolha como aceder às suas notas encriptadas" },
                { "password_fair", "Razoável" },
                { "master_password_label", "Senha mestre:" },
                { "confirm_password_label", "Confirmar senha:" },
                { "create_new_vault_desc", "Crie uma senha mestre e escolha onde guardar o seu cofre .kdbx encriptado. Este ficheiro é compatível com KeePass e a app Secure Notes para Android." },
                { "no_vault_found", "Nenhum cofre encontrado. Por favor, abra ou crie um." },
                { "incorrect_password_vault", "Senha incorreta ou cofre corrompido." },
                { "failed_to_create_vault", "Falha ao criar o cofre. Verifique as permissões." },
                { "please_enter_password", "Por favor, introduza uma senha." },
                { "create_vault_ellipsis", "Criar cofre\u2026" },
                { "create_new_vault_ellipsis", "Criar novo cofre\u2026" },
                { "backup_to_zip_sub", "Salvar todas as notas como backup ZIP Markdown" },
                { "restore_from_zip_sub", "Restaurar notas de um backup ZIP Markdown" },
                { "import_journey", "Importar do Journey" },
                { "import_dayone", "Importar do DayOne" },
                { "import_journey_sub", "Importar diário Journey.cloud (ZIP JSON)" },
                { "import_dayone_sub", "Importar diário DayOne (ZIP JSON)" },
                { "backup_book_selector_title", "Fazer backup de qual caderno?" },
                { "restore_book_selector_title", "Restaurar para qual caderno?" },
                { "import_book_selector_title", "Importar {0} para qual caderno?" },
                { "backup_success", "Backup concluído." },
                { "restore_success", "{0} nota(s) restaurada(s)." },
                { "import_success", "{0} nota(s) importada(s) de {1}." },
                { "date_format", "Formato de Data" },
                { "time_format", "Formato de Hora" },
                { "general", "Geral" },
                { "lock_vault", "Bloquear cofre" },
                { "select_date_format", "Selecionar formato de data" },
{ "select_time_format", "Selecionar formato de hora" },
{ "select_theme", "Selecionar tema" },
{ "import_to_which_book", "Importar para qual livro?" },
{ "import_complete", "Importação concluída" },
{ "imported_notes", "{0} nota(s) importada(s)." },
{ "imported_notes_from", "{0} nota(s) importada(s) de {1}." },
{ "export_which_book", "Exportar qual livro?" },
{ "export_complete", "Exportação concluída" },
{ "import", "Importar" },
{ "export", "Exportar" },
{ "error", "Erro" },
{ "current_password_incorrect", "A senha atual está incorreta." },
{ "password_changed_successfully", "Senha alterada com sucesso." },
{ "failed_change_password", "Falha ao alterar a senha." },
{ "import_from", "Importar de {0}" },
{ "import_to_book", "Importar {0} para qual livro?" },
{ "enter_current_password_error", "Por favor, introduza a sua senha atual." },
{ "new_password_too_short", "A nova senha deve ter pelo menos 6 caracteres." },
{ "passwords_do_not_match", "As senhas não coincidem." },
{ "new_password", "Nova senha" },
{ "confirm_new_password", "Confirmar nova senha" },
{ "change", "Alterar" },
{ "current_password", "Senha atual" },
{ "auto_lock_timeout", "Tempo limite de bloqueio automático" },
{ "lock_after_inactivity", "Bloquear cofre após inatividade" },
{ "minutes", "Minutos" },
{ "seconds", "Segundos" },
            
                { "rename", "Editar" },
                { "edit", "Editar" },
                { "rename_book", "Editar Livro" },
                { "notebook", "Caderno" },
                { "diary", "Diário" },
                { "yes", "Sim" },
                { "yes_delete", "Sim, Eliminar" },
                { "no", "Não" },
                { "delete_note_title", "Eliminar Nota" },
                { "add_book", "Adicionar Livro" },
                { "manage_tags", "Gerir Etiquetas" },
                { "select_or_create", "Selecionar ou criar uma nota" },
                { "move_to_book", "Mover para Livro" },
                { "which_book", "Para qual livro deseja mover?" },
                { "move_btn", "Mover" },
            
                { "add", "Adicionar" },
                { "edit_notebook", "Editar Caderno" },
                { "name", "Nome" },
            
                { "icon", "Ícone" },
            };

            // Russian
            _translations[AppLanguage.RUSSIAN] = new Dictionary<string, string>
            {
                { "settings", "Настройки" },
                { "appearance", "Внешний вид" },
                { "theme", "Тема" },
                { "security", "Безопасность" },
                { "auto_lock", "Автоблокировка" },
                { "change_password", "Изменить мастер-пароль" },
                { "backup_restore", "РЕЗЕРВНОЕ КОПИРОВАНИЕ И ВОССТАНОВЛЕНИЕ" },
                { "import_section", "ИМПОРТ" },
                { "backup_to_zip", "Создать резервную копию в Zip" },
                { "restore_from_zip", "Восстановить из Zip" },
                { "about", "О программе" },
                { "version", "Версия" },
                { "language", "Язык" },
                { "select_language", "Выберите язык" },
                { "cancel", "Отмена" },
                { "save", "Сохранить" },
                { "done", "Готово" },
                { "close", "Закрыть" },
                { "search_notes", "Поиск заметок..." },
                { "no_notes", "Заметок пока нет\nСоздайте книгу, а затем добавьте свои заметки" },
                { "unlock_vault", "Разблокировать хранилище" },
                { "master_password", "Мастер-пароль" },
                { "create_vault", "Создать хранилище" },
                { "secure_notes", "Безопасные заметки" },
                { "new_note", "Новая заметка" },
                { "new_diary", "Новая запись в дневнике" },
                { "delete", "Удалить" },
                { "books", "КНИГИ" },
                { "ink_black", "Чернильно-черный" },
                { "paper_white", "Бумажный белый" },
                { "light_mode", "Светлая тема" },
                { "dark_mode", "Темная тема" },
                { "follow_system", "Как в системе" },
                { "update_vault_password", "Обновить пароль хранилища" },
                { "open_vault", "Открыть хранилище" },
                { "create_new_vault", "Создать новое хранилище" },
                { "open_existing_vault", "Открыть существующее хранилище" },
                { "choose_vault_access", "Выберите способ доступа к зашифрованным заметкам" },
                { "password_fair", "Слабый" },
                { "master_password_label", "Мастер-пароль:" },
                { "confirm_password_label", "Подтвердите пароль:" },
                { "create_new_vault_desc", "Создайте мастер-пароль и выберите, где хранить ваше зашифрованное хранилище .kdbx. Файл совместим с KeePass и приложением Secure Notes для Android." },
                { "no_vault_found", "Хранилище не найдено. Откройте или создайте его." },
                { "incorrect_password_vault", "Неверный пароль или повреждённое хранилище." },
                { "failed_to_create_vault", "Не удалось создать хранилище. Проверьте разрешения." },
                { "please_enter_password", "Пожалуйста, введите пароль." },
                { "create_vault_ellipsis", "Создать хранилище\u2026" },
                { "create_new_vault_ellipsis", "Создать новое хранилище\u2026" },
                { "backup_to_zip_sub", "Сохранить все заметки как резервную копию в ZIP" },
                { "restore_from_zip_sub", "Восстановить заметки из резервной копии ZIP" },
                { "import_journey", "Импорт из Journey" },
                { "import_dayone", "Импорт из DayOne" },
                { "import_journey_sub", "Импортировать дневник Journey.cloud (JSON ZIP)" },
                { "import_dayone_sub", "Импортировать дневник DayOne (JSON ZIP)" },
                { "backup_book_selector_title", "Из какого блокнота создать резервную копию?" },
                { "restore_book_selector_title", "В какой блокнот восстановить?" },
                { "import_book_selector_title", "Импортировать {0} в какой блокнот?" },
                { "backup_success", "Резервное копирование завершено." },
                { "restore_success", "Восстановлено {0} заметок." },
                { "import_success", "Импортировано {0} заметок из {1}." },
                { "date_format", "Формат даты" },
                { "time_format", "Формат времени" },
                { "general", "Основные" },
                { "lock_vault", "Заблокировать хранилище" },
                { "select_date_format", "Выберите формат даты" },
{ "select_time_format", "Выберите формат времени" },
{ "select_theme", "Выберите тему" },
{ "import_to_which_book", "В какую книгу импортировать?" },
{ "import_complete", "Импорт завершён" },
{ "imported_notes", "Импортировано {0} заметок." },
{ "imported_notes_from", "Импортировано {0} заметок из {1}." },
{ "export_which_book", "Какую книгу экспортировать?" },
{ "export_complete", "Экспорт завершён" },
{ "import", "Импорт" },
{ "export", "Экспорт" },
{ "error", "Ошибка" },
{ "current_password_incorrect", "Текущий пароль неверный." },
{ "password_changed_successfully", "Пароль успешно изменён." },
{ "failed_change_password", "Не удалось изменить пароль." },
{ "import_from", "Импорт из {0}" },
{ "import_to_book", "Импортировать {0} в какую книгу?" },
{ "enter_current_password_error", "Пожалуйста, введите текущий пароль." },
{ "new_password_too_short", "Новый пароль должен содержать не менее 6 символов." },
{ "passwords_do_not_match", "Пароли не совпадают." },
{ "new_password", "Новый пароль" },
{ "confirm_new_password", "Подтвердите новый пароль" },
{ "change", "Изменить" },
{ "current_password", "Текущий пароль" },
{ "auto_lock_timeout", "Тайм-аут автоблокировки" },
{ "lock_after_inactivity", "Блокировать хранилище после бездействия" },
{ "minutes", "Минуты" },
{ "seconds", "Секунды" },
            
                { "rename", "Редактировать" },
                { "edit", "Редактировать" },
                { "rename_book", "Редактировать Книгу" },
                { "notebook", "Блокнот" },
                { "diary", "Дневник" },
                { "yes", "Да" },
                { "yes_delete", "Да, Удалить" },
                { "no", "Нет" },
                { "delete_note_title", "Удалить Заметку" },
                { "add_book", "Добавить Книгу" },
                { "manage_tags", "Управление Тегами" },
                { "select_or_create", "Выберите или создайте заметку" },
                { "move_to_book", "Переместить в Книгу" },
                { "which_book", "В какую книгу вы хотите переместить?" },
                { "move_btn", "Переместить" },
            
                { "add", "Добавить" },
                { "edit_notebook", "Редактировать Блокнот" },
                { "name", "Название" },
            
                { "icon", "Значок" },
            };

            // Bengali
            _translations[AppLanguage.BENGALI] = new Dictionary<string, string>
            {
                { "settings", "সেটিংস" },
                { "appearance", "চেহারা" },
                { "theme", "থিম" },
                { "security", "নিরাপত্তা" },
                { "auto_lock", "অটো-লক" },
                { "change_password", "মাস্টার পাসওয়ার্ড পরিবর্তন করুন" },
                { "backup_restore", "ব্যাকআপ ও পুনরুদ্ধার" },
                { "import_section", "ইম্পোর্ট" },
                { "backup_to_zip", "Zip-এ ব্যাকআপ করুন" },
                { "restore_from_zip", "Zip থেকে পুনরুদ্ধার করুন" },
                { "about", "সম্পর্কে" },
                { "version", "সংস্করণ" },
                { "language", "ভাষা" },
                { "select_language", "ভাষা নির্বাচন করুন" },
                { "cancel", "বাতিল" },
                { "save", "সংরক্ষণ" },
                { "done", "সম্পন্ন" },
                { "close", "বন্ধ করুন" },
                { "search_notes", "নোট খুঁজুন..." },
                { "unlock_vault", "ভল্ট আনলক করুন" },
                { "master_password", "মাস্টার পাসওয়ার্ড" },
                { "create_vault", "ভল্ট তৈরি করুন" },
                { "secure_notes", "সিকিউর নোটস" },
                { "new_note", "নতুন নোট" },
                { "new_diary", "নতুন ডায়েরি" },
                { "delete", "মুছে ফেলুন" },
                { "books", "বই" },
                { "ink_black", "কালি কালো" },
                { "paper_white", "কাগজ সাদা" },
                { "update_vault_password", "আপনার ভল্টের পাসওয়ার্ড আপডেট করুন" },
                { "open_vault", "ভল্ট খুলুন" },
                { "create_new_vault", "নতুন ভল্ট তৈরি করুন" },
                { "open_existing_vault", "বিদ্যমান ভল্ট খুলুন" },
                { "choose_vault_access", "আপনার এনক্রিপ্টেড নোট অ্যাক্সেস করার উপায় বেছে নিন" },
                { "password_fair", "মাঝারি" },
                { "master_password_label", "মাস্টার পাসওয়ার্ড:" },
                { "confirm_password_label", "পাসওয়ার্ড নিশ্চিত করুন:" },
                { "create_new_vault_desc", "একটি মাস্টার পাসওয়ার্ড তৈরি করুন এবং আপনার এনক্রিপ্টেড .kdbx ভল্ট কোথায় সংরক্ষণ করবেন তা বেছে নিন। এই ফাইলটি KeePass এবং Secure Notes Android অ্যাপের সাথে সামঞ্জস্যপূর্ণ।" },
                { "no_vault_found", "কোন ভল্ট পাওয়া যায়নি। অনুগ্রহ করে একটি খুলুন বা তৈরি করুন।" },
                { "incorrect_password_vault", "ভুল পাসওয়ার্ড বা ক্ষতিগ্রস্ত ভল্ট।" },
                { "failed_to_create_vault", "ভল্ট তৈরি করতে ব্যর্থ হয়েছে। অনুমতি পরীক্ষা করুন।" },
                { "please_enter_password", "অনুগ্রহ করে একটি পাসওয়ার্ড লিখুন।" },
                { "create_vault_ellipsis", "ভল্ট তৈরি করুন\u2026" },
                { "create_new_vault_ellipsis", "নতুন ভল্ট তৈরি করুন\u2026" },
                { "backup_to_zip_sub", "সমস্ত নোট Markdown ZIP হিসেবে সংরক্ষণ করুন" },
                { "restore_from_zip_sub", "Markdown ZIP থেকে নোট পুনরুদ্ধার করুন" },
                { "import_journey", "Journey থেকে ইম্পোর্ট করুন" },
                { "import_dayone", "DayOne থেকে ইম্পোর্ট করুন" },
                { "import_journey_sub", "Journey.cloud ডায়েরি ইম্পোর্ট করুন (JSON ZIP)" },
                { "import_dayone_sub", "DayOne ডায়েরি ইম্পোর্ট করুন (JSON ZIP)" },
                { "backup_book_selector_title", "কোন বই ব্যাকআপ করবেন?" },
                { "restore_book_selector_title", "কোন বইতে পুনরুদ্ধার করবেন?" },
                { "import_book_selector_title", "{0} কোন বইতে ইম্পোর্ট করবেন?" },
                { "backup_success", "ব্যাকআপ সম্পন্ন হয়েছে।" },
                { "restore_success", "{0}টি নোট পুনরুদ্ধার হয়েছে।" },
                { "import_success", "{1} থেকে {0}টি নোট ইম্পোর্ট হয়েছে।" },
                { "date_format", "তারিখ ফরম্যাট" },
                { "time_format", "সময় ফরম্যাট" },
                { "general", "সাধারণ" },
                { "lock_vault", "ভল্ট লক করুন" },
                { "select_date_format", "তারিখের ফরম্যাট নির্বাচন করুন" },
{ "select_time_format", "সময়ের ফরম্যাট নির্বাচন করুন" },
{ "select_theme", "থিম নির্বাচন করুন" },
{ "import_to_which_book", "কোন বইতে ইম্পোর্ট করবেন?" },
{ "import_complete", "ইম্পোর্ট সম্পন্ন" },
{ "imported_notes", "{0}টি নোট ইম্পোর্ট করা হয়েছে।" },
{ "imported_notes_from", "{0}টি নোট {1} থেকে ইম্পোর্ট করা হয়েছে।" },
{ "export_which_book", "কোন বই এক্সপোর্ট করবেন?" },
{ "export_complete", "এক্সপোর্ট সম্পন্ন" },
{ "import", "ইম্পোর্ট" },
{ "export", "এক্সপোর্ট" },
{ "error", "ত্রুটি" },
{ "current_password_incorrect", "বর্তমান পাসওয়ার্ড ভুল।" },
{ "password_changed_successfully", "পাসওয়ার্ড সফলভাবে পরিবর্তন হয়েছে।" },
{ "failed_change_password", "পাসওয়ার্ড পরিবর্তন ব্যর্থ হয়েছে।" },
{ "import_from", "{0} থেকে ইম্পোর্ট করুন" },
{ "import_to_book", "{0} কোন বইতে ইম্পোর্ট করবেন?" },
{ "enter_current_password_error", "অনুগ্রহ করে আপনার বর্তমান পাসওয়ার্ড লিখুন।" },
{ "new_password_too_short", "নতুন পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।" },
{ "passwords_do_not_match", "পাসওয়ার্ড মিলছে না।" },
{ "new_password", "নতুন পাসওয়ার্ড" },
{ "confirm_new_password", "নতুন পাসওয়ার্ড নিশ্চিত করুন" },
{ "change", "পরিবর্তন করুন" },
{ "current_password", "বর্তমান পাসওয়ার্ড" },
{ "auto_lock_timeout", "অটো-লক টাইমআউট" },
{ "lock_after_inactivity", "নিষ্ক্রিয়তার পরে ভল্ট লক করুন" },
{ "minutes", "মিনিট" },
{ "seconds", "সেকেন্ড" },
            
                { "rename", "সম্পাদনা করুন" },
                { "edit", "সম্পাদনা করুন" },
                { "rename_book", "বই সম্পাদনা করুন" },
                { "notebook", "নোটবুক" },
                { "diary", "ডায়েরি" },
                { "yes", "হ্যাঁ" },
                { "yes_delete", "হ্যাঁ, মুছুন" },
                { "no", "না" },
                { "delete_note_title", "নোট মুছুন" },
                { "add_book", "বই যোগ করুন" },
                { "manage_tags", "ট্যাগ পরিচালনা" },
                { "select_or_create", "একটি নোট নির্বাচন বা তৈরি করুন" },
                { "move_to_book", "বইতে সরান" },
                { "which_book", "কোন বইতে সরাতে চান?" },
                { "move_btn", "সরান" },
            
                { "add", "যোগ করুন" },
                { "edit_notebook", "নোটবুক সম্পাদনা করুন" },
                { "name", "নাম" },
            
                { "icon", "আইকন" },
            };

            // Hindi
            _translations[AppLanguage.HINDI] = new Dictionary<string, string>
            {
                { "settings", "सेटिंग्स" },
                { "appearance", "दिखावट" },
                { "theme", "थीम" },
                { "security", "सुरक्षा" },
                { "auto_lock", "ऑटो-लॉक" },
                { "change_password", "मास्टर पासवर्ड बदलें" },
                { "backup_restore", "बैकअप और पुनर्स्थापना" },
                { "import_section", "आयात" },
                { "backup_to_zip", "Zip में बैकअप करें" },
                { "restore_from_zip", "Zip से पुनर्स्थापित करें" },
                { "about", "विवरण" },
                { "version", "संस्करण" },
                { "language", "भाषा" },
                { "select_language", "भाषा चुनें" },
                { "cancel", "रद्द करें" },
                { "save", "सहेजें" },
                { "done", "हो गया" },
                { "close", "बंद करें" },
                { "search_notes", "नोट्स खोजें..." },
                { "unlock_vault", "वॉल्ट अनलॉक करें" },
                { "master_password", "मास्टर पासवर्ड" },
                { "create_vault", "वॉल्ट बनाएँ" },
                { "secure_notes", "सिक्योर नोट्स" },
                { "new_note", "नया नोट" },
                { "new_diary", "नई डायरी" },
                { "delete", "हटाएँ" },
                { "books", "किताबें" },
                { "ink_black", "स्याही जैसा काला" },
                { "paper_white", "कागज जैसा सफेद" },
                { "update_vault_password", "अपना vault पासवर्ड अपडेट करें" },
                { "open_vault", "वॉल्ट खोलें" },
                { "create_new_vault", "नया वॉल्ट बनाएँ" },
                { "open_existing_vault", "मौजूदा वॉल्ट खोलें" },
                { "choose_vault_access", "अपनी एन्क्रिप्टेड नोट्स तक पहुँचने का तरीका चुनें" },
                { "password_fair", "ठीक-ठाक" },
                { "master_password_label", "मास्टर पासवर्ड:" },
                { "confirm_password_label", "पासवर्ड की पुष्टि करें:" },
                { "create_new_vault_desc", "एक मास्टर पासवर्ड बनाएँ और चुनें कि अपना एन्क्रिप्टेड .kdbx वॉल्ट कहाँ संग्रहीत करें। यह फ़ाइल KeePass और Secure Notes Android ऐप के साथ संगत है।" },
                { "no_vault_found", "कोई वॉल्ट नहीं मिला। कृपया एक खोलें या बनाएँ।" },
                { "incorrect_password_vault", "गलत पासवर्ड या दूषित वॉल्ट।" },
                { "failed_to_create_vault", "वॉल्ट बनाने में विफल। अनुमतियाँ जाँचें।" },
                { "please_enter_password", "कृपया एक पासवर्ड दर्ज करें।" },
                { "create_vault_ellipsis", "वॉल्ट बनाएँ\u2026" },
                { "create_new_vault_ellipsis", "नया वॉल्ट बनाएँ\u2026" },
                { "backup_to_zip_sub", "सभी नोट्स को Markdown ZIP बैकअप के रूप में सहेजें" },
                { "restore_from_zip_sub", "Markdown ZIP बैकअप से नोट्स पुनर्स्थापित करें" },
                { "import_journey", "Journey से आयात करें" },
                { "import_dayone", "DayOne से आयात करें" },
                { "import_journey_sub", "Journey.cloud डायरी आयात करें (JSON ZIP)" },
                { "import_dayone_sub", "DayOne डायरी आयात करें (JSON ZIP)" },
                { "backup_book_selector_title", "किस पुस्तक का बैकअप लें?" },
                { "restore_book_selector_title", "किस पुस्तक में पुनर्स्थापित करें?" },
                { "import_book_selector_title", "{0} को किस पुस्तक में आयात करें?" },
                { "backup_success", "बैकअप पूर्ण हुआ।" },
                { "restore_success", "{0} नोट पुनर्स्थापित हुए।" },
                { "import_success", "{1} से {0} नोट आयात हुए।" },
                { "date_format", "दिनांक प्रारूप" },
                { "time_format", "समय प्रारूप" },
                { "general", "सामान्य" },
                { "lock_vault", "वॉल्ट लॉक करें" },
                { "select_date_format", "दिनांक प्रारूप चुनें" },
{ "select_time_format", "समय प्रारूप चुनें" },
{ "select_theme", "थीम चुनें" },
{ "import_to_which_book", "किस किताब में इम्पोर्ट करें?" },
{ "import_complete", "इम्पोर्ट पूरा हुआ" },
{ "imported_notes", "{0} नोट्स इम्पोर्ट किए गए।" },
{ "imported_notes_from", "{0} नोट्स {1} से इम्पोर्ट किए गए।" },
{ "export_which_book", "कौन सी किताब एक्सपोर्ट करें?" },
{ "export_complete", "एक्सपोर्ट पूरा हुआ" },
{ "import", "इम्पोर्ट" },
{ "export", "एक्सपोर्ट" },
{ "error", "त्रुटि" },
{ "current_password_incorrect", "वर्तमान पासवर्ड गलत है।" },
{ "password_changed_successfully", "पासवर्ड सफलतापूर्वक बदल दिया गया।" },
{ "failed_change_password", "पासवर्ड बदलने में विफल।" },
{ "import_from", "{0} से इम्पोर्ट करें" },
{ "import_to_book", "{0} किस किताब में इम्पोर्ट करें?" },
{ "enter_current_password_error", "कृपया अपना वर्तमान पासवर्ड दर्ज करें।" },
{ "new_password_too_short", "नया पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।" },
{ "passwords_do_not_match", "पासवर्ड मेल नहीं खाते।" },
{ "new_password", "नया पासवर्ड" },
{ "confirm_new_password", "नए पासवर्ड की पुष्टि करें" },
{ "change", "बदलें" },
{ "current_password", "वर्तमान पासवर्ड" },
{ "auto_lock_timeout", "ऑटो-लॉक टाइमआउट" },
{ "lock_after_inactivity", "निष्क्रियता के बाद वॉल्ट लॉक करें" },
{ "minutes", "मिनट" },
{ "seconds", "सेकंड" },
            
                { "rename", "संपादित करें" },
                { "edit", "संपादित करें" },
                { "rename_book", "किताब संपादित करें" },
                { "notebook", "नोटबुक" },
                { "diary", "डायरी" },
                { "yes", "हाँ" },
                { "yes_delete", "हाँ, हटाएँ" },
                { "no", "नहीं" },
                { "delete_note_title", "नोट हटाएँ" },
                { "add_book", "किताब जोड़ें" },
                { "manage_tags", "टैग प्रबंधित करें" },
                { "select_or_create", "एक नोट चुनें या बनाएँ" },
                { "move_to_book", "किताब में ले जाएँ" },
                { "which_book", "किस किताब में ले जाना चाहते हैं?" },
                { "move_btn", "ले जाएँ" },
            
                { "add", "जोड़ें" },
                { "edit_notebook", "नोटबुक संपादित करें" },
                { "name", "नाम" },
            
                { "icon", "आइकन" },
            };

            // Chinese Mandarin
            _translations[AppLanguage.CHINESE_MANDARIN] = new Dictionary<string, string>
            {
                { "settings", "设置" },
                { "appearance", "外观" },
                { "theme", "主题" },
                { "security", "安全" },
                { "auto_lock", "自动锁定" },
                { "change_password", "修改主密码" },
                { "backup_restore", "备份与恢复" },
                { "import_section", "导入" },
                { "backup_to_zip", "备份到 Zip" },
                { "restore_from_zip", "从 Zip 恢复" },
                { "about", "关于" },
                { "version", "版本" },
                { "language", "语言" },
                { "select_language", "选择语言" },
                { "cancel", "取消" },
                { "save", "保存" },
                { "done", "完成" },
                { "close", "关闭" },
                { "search_notes", "搜索笔记..." },
                { "unlock_vault", "解锁保险库" },
                { "master_password", "主密码" },
                { "create_vault", "创建保险库" },
                { "secure_notes", "安全笔记" },
                { "new_note", "新建笔记" },
                { "new_diary", "新建日记" },
                { "delete", "删除" },
                { "books", "笔记本" },
                { "ink_black", "墨黑" },
                { "paper_white", "纸白" },
                { "update_vault_password", "更新您的保险库密码" },
                { "open_vault", "打开保险库" },
                { "create_new_vault", "创建新保险库" },
                { "open_existing_vault", "打开现有保险库" },
                { "choose_vault_access", "选择访问加密笔记的方式" },
                { "password_fair", "一般" },
                { "master_password_label", "主密码：" },
                { "confirm_password_label", "确认密码：" },
                { "create_new_vault_desc", "创建主密码并选择存储加密 .kdbx 保险库的位置。此文件与 KeePass 和 Secure Notes Android 应用兼容。" },
                { "no_vault_found", "未找到保险库，请打开或创建一个。" },
                { "incorrect_password_vault", "密码错误或保险库已损坏。" },
                { "failed_to_create_vault", "创建保险库失败，请检查权限。" },
                { "please_enter_password", "请输入密码。" },
                { "create_vault_ellipsis", "创建保险库\u2026" },
                { "create_new_vault_ellipsis", "创建新保险库\u2026" },
                { "backup_to_zip_sub", "将所有笔记保存为 Markdown ZIP 备份" },
                { "restore_from_zip_sub", "从 Markdown ZIP 备份中恢复笔记" },
                { "import_journey", "从 Journey 导入" },
                { "import_dayone", "从 DayOne 导入" },
                { "import_journey_sub", "导入 Journey.cloud 日记（JSON ZIP）" },
                { "import_dayone_sub", "导入 DayOne 日记（JSON ZIP）" },
                { "backup_book_selector_title", "备份哪个笔记本？" },
                { "restore_book_selector_title", "恢复到哪个笔记本？" },
                { "import_book_selector_title", "将 {0} 导入哪个笔记本？" },
                { "backup_success", "备份完成。" },
                { "restore_success", "已恢复 {0} 条笔记。" },
                { "import_success", "已从 {1} 导入 {0} 条笔记。" },
                { "date_format", "日期格式" },
                { "time_format", "时间格式" },
                { "general", "常规" },
                { "lock_vault", "锁定保险库" },
                { "select_date_format", "选择日期格式" },
{ "select_time_format", "选择时间格式" },
{ "select_theme", "选择主题" },
{ "import_to_which_book", "导入到哪本书？" },
{ "import_complete", "导入完成" },
{ "imported_notes", "已导入 {0} 条笔记。" },
{ "imported_notes_from", "已从 {1} 导入 {0} 条笔记。" },
{ "export_which_book", "导出哪本书？" },
{ "export_complete", "导出完成" },
{ "import", "导入" },
{ "export", "导出" },
{ "error", "错误" },
{ "current_password_incorrect", "当前密码不正确。" },
{ "password_changed_successfully", "密码修改成功。" },
{ "failed_change_password", "修改密码失败。" },
{ "import_from", "从 {0} 导入" },
{ "import_to_book", "将 {0} 导入到哪本书？" },
{ "enter_current_password_error", "请输入当前密码。" },
{ "new_password_too_short", "新密码至少需要6个字符。" },
{ "passwords_do_not_match", "两次输入的密码不一致。" },
{ "new_password", "新密码" },
{ "confirm_new_password", "确认新密码" },
{ "change", "更改" },
{ "current_password", "当前密码" },
{ "auto_lock_timeout", "自动锁定超时" },
{ "lock_after_inactivity", "无操作后锁定保险库" },
{ "minutes", "分钟" },
{ "seconds", "秒" },
            
                { "rename", "编辑" },
                { "edit", "编辑" },
                { "rename_book", "编辑笔记本" },
                { "notebook", "笔记本" },
                { "diary", "日记" },
                { "yes", "是" },
                { "yes_delete", "是，删除" },
                { "no", "否" },
                { "delete_note_title", "删除笔记" },
                { "add_book", "添加笔记本" },
                { "manage_tags", "管理标签" },
                { "select_or_create", "选择或创建笔记" },
                { "move_to_book", "移至笔记本" },
                { "which_book", "要移动到哪本笔记本？" },
                { "move_btn", "移动" },
            
                { "add", "添加" },
                { "edit_notebook", "编辑笔记本" },
                { "name", "名称" },
            
                { "icon", "图标" },
            };
        }

        /// <summary>
        /// Gets all translations for a given language.
        /// Returns a copy to prevent external modification of internal state.
        /// </summary>
        public Dictionary<string, string> GetTranslationsForLanguage(AppLanguage language)
        {
            if (_translations.TryGetValue(language, out var translations))
            {
                // Return a COPY to prevent external code from modifying the original
                return new Dictionary<string, string>(translations);
            }
            // Return a copy of English as fallback
            return new Dictionary<string, string>(_translations[AppLanguage.ENGLISH]);
        }

        public string GetString(string key, params object[] args)
        {
            if (_translations.TryGetValue(_currentLanguage, out var dict) && dict.TryGetValue(key, out var value))
            {
                return args.Length > 0 ? string.Format(value, args) : value;
            }

            // Fallback to English
            if (_translations[AppLanguage.ENGLISH].TryGetValue(key, out var fallback))
            {
                return args.Length > 0 ? string.Format(fallback, args) : fallback;
            }

            return key;
        }

        protected void OnPropertyChanged([CallerMemberName] string? name = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }
    }

    // Binding helper for XAML (legacy support)
    public class LocalizationBindingExtension : System.Windows.Data.Binding
    {
        public LocalizationBindingExtension(string key)
        {
            Source = LocalizationManager.Instance;
            Path = new System.Windows.PropertyPath($"Item[{key}]");
            Mode = System.Windows.Data.BindingMode.OneWay;
            UpdateSourceTrigger = System.Windows.Data.UpdateSourceTrigger.PropertyChanged;
        }
    }
}